apiVersion: v1
kind: Service
metadata:
  name: prometheus-spring-actuator
  labels:
    run: prometheus-spring-actuator
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: prometheus-spring-actuator
